### ISSUE TITLE
Is there any way to make searchable on rails 4 enum attribute.

### ISSUE THREAD

**Issue by codemilan** [jbox-web/ajax-datatables-rails#109]
I have column pic_type in a table, with integer type, which is mapped to ActiveRecord as enum attribute. Now how can we search and return records for this attribute by searching 'string'(equivalent to enum values) value in datatable search box.

**Comment by antillas21** [comment]
As of right you can't. The reason is, in your db engine you have a column
of type Integer, that in your app domain is mapped to an enum yes, but
that's in your app's code, not your db engine, and the gem pulls your db
column to perform searches.

This is a very interesting scenario, and would like to invite you to
contribute a solution for this. What do you say?

**Comment by codemilan** [comment]
thanks @antillas21, for quick response, actually I'm new to rails and ruby, I think, I can't contribute now, but will try my best in near future, will take it as a challenge from now onwards.

**Comment by antillas21** [comment]
@coderawal Looking forward for a contribution from you in the future :smile: 

Related to this, I just received this in the mail: http://www.justinweiss.com/blog/2015/06/30/creating-easy-readable-attributes-with-activerecord-enums/
which basically, describes the problem of using `enum` in an app's code. Not that it's a bad idea, but it has some cons when it comes to accessing data directly from the db.
