### ISSUE TITLE
Allow database query to use exact ('equal_to') and not just 'like' matchers on search

### ISSUE THREAD

**Issue by innocentamadi** [jbox-web/ajax-datatables-rails#176]
In my specific condition, I wanted to find the exact occurrence of a specific order number in the database. The client didn't want to see any other orders apart from the order searched for. I needed an exact match.

When I typed the order number in search, I noticed it fires a 'LIKE' query. It would be nice if there was an option to fire an 'equal to' matcher instead.

**Comment by innocentamadi** [comment]
I could work on this if there is no existing solution, or no one else is currently on something similar.

**Comment by antillas21** [comment]
There is work done on this front in the v-0-4-0 branch... you could check
it out

On Sep 15, 2016 20:08, "Innocent Amadi" notifications@github.com wrote:

I could work on this if there is no existing solution, or no one else is
currently on something similar.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/antillas21/ajax-datatables-rails/issues/176#issuecomment-247508329,
or mute the thread

**Comment by innocentamadi** [comment]
The `non_regex_search` method in the v-0-4-0 branch implements even better that what I had in mind! More options are definitely supported. Awesome!

Any ideas when it would ship? I'm currently overriding the `search_condition` method (my conscience keeps pricking me because the method is private)

**Comment by ajahongir** [comment]
also you can check out the how-to project - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by innocentamadi** [comment]
Thanks a lot for the how-to project. It would save me time on trial and error.

I'd go ahead and use the  v-0-4-0 branch then. And I'd close this issue now. Thanks again for the support. You guys are amazing!

**Comment by antillas21** [comment]
All credit really goes to Jackhongir :D
