### ISSUE TITLE
Change sortable/searchable syntax

### ISSUE THREAD

**Issue by MattRogish** [jbox-web/ajax-datatables-rails#19]
It seems odd and extra verbose to repeat the model name in the sortable/searchable columns. Instead of [ 'users.f_name', 'users.l_name' ] etc. why not use a Rails convention and derive it from the class name of the UsersDatatable? Then, the column list could be anything, symbols, strings, whatever. e.g. @columns ||= %w(a b c) # this is way easier to type

It seems like this wouldn't be too difficult, and I'm happy to do it and open a PR, but only if it won't be rejected on design grounds. Thanks!

**Comment by antillas21** [comment]
Hi @MattRogish ,

First of all, an apology for not getting back at you earlier. I was mostly offline last week while attending a conference in a "somewhat remote area".

I am definitively interested in refining the issue for specifying `sortable_columns` and `searchable_columns` as long as the following is taken into account:

Suppose you need to make a query that joins/includes data from a table (e.g. `users`) as well as data from a related model table (e.g. `subscriptions`), and present them like this:

| first name | last name | subscription plan | subscription price |
| --- | --- | --- | --- |
| John | Doe | Regular | 1.00 |
| Jane | Doe | Prime | 10.00 |

Where the first two columns are taken from the `users` table and the last two columns are taken from the `subscriptions` table.

So, in the end, this type of query (which is what I'm mostly interested in, to provide flexibility to developers) does not rely on only one model table to query/sort records. This is for the moment, the reason it was decided to define columns like it is (currently in the README file), until further testing and reading is done to come up with a more db agnostic way of doing so.

What do you say? Does this look interesting enough to contribute to this little gem? :smile:

**Comment by MattRogish** [comment]
I think that makes sense (sorry for the delay on my part, too!). If you just pass the strings on to the SQL DBMS, it'll handle disambiguation. If there are multiple tables with columns of same name, it'll throw an error. If not, it'll "just work". Why take on all that effort yourself? :)

That is, specifying WHERE last_name = 'ABC123' will work fine, unless subscriptions also has it, and the database will throw an exception, reminding the user to type "users.last_name".

**Comment by antillas21** [comment]
Hey @MattRogish ,

Thanks for the clarification... I would like to ask what version of ActiveRecord will "just work" if I omit the table name as prefix.

The reason, is because I remember being bitten by ActiveRecord when working on Rails 3.1, 3.2 when joining tables and trying to perform searches or sorting based on columns from joined tables.

If you take a look at the `gemspec` file, the idea is to support from Rails 3.1 and up. Yes, we may say that 3.2.x is the only one to be considered as legacy and should be supported aside from Rails 4.x... but believe me, there are still people working on old Rails versions... I personally, maintain 2 apps that given stakeholders constraints work under Rails 1.2.6 and Rails 3.0.20.

But, enough background info... I guess it's best for the gem to remove unnecessary code when applicable. So, if you can provide tests under the scenarios described in my earlier comment, targeting  Rails 3.1 and up, so we can assert we can safely remove such assumption... then let's remove it :smile:

What do you say?

**Comment by antillas21** [comment]
Closing due to lack of response.
