### ISSUE TITLE
Still maintain?

### ISSUE THREAD

**Issue by n-rodriguez** [jbox-web/ajax-datatables-rails#215]
Hi there! Is this project still maintain?

**Comment by alessiovaralta** [comment]
Hi, I send an email to ask this question but I don't have the answer.
I think is important because if I use this gem in a project in my company is a big problem if is not mantain. 
For example now there is the new version on branch v-0-4-0.
But this version is not compatible with rails 3.2...and is updated 9 months ago..

**Comment by antillas21** [comment]
@n-rodriguez I've been really busy for the last year or so (due to work, parental responsibilities and every day life), and haven't really have had energy to continue working on this gem since then.

Recently I made up my mind, and have decided to end my involvement in this gem's development. If there would be people interested in taking ownership and continue working on this gem's code and features, I am open to discus/transfer this little gem's work.

I believe I received an email from you @n-rodriguez (almost a month ago), right? If you're still interested in becoming the new owner of this gem, let's talk.

**Comment by SampsonCrowley** [comment]
@antillas21 I also could take over if @n-rodriguez does not want to

**Comment by n-rodriguez** [comment]
@SampsonCrowley done! Welcome in the team!
