### ISSUE TITLE
Call datatable class from external module

### ISSUE THREAD

**Issue by alessiovaralta** [jbox-web/ajax-datatables-rails#255]
I have a rails 3.2 application where I use differents gem that I have created. I have a folder People and a folder Magazine, so in people I have a file

```
module Essa::Person
 class CarsDatatable < AjaxDatatablesRails::Base
```
I want to call CarsDatatable in a external module. How is the syntax to initialize CarsDatatable in a controller of the folder Magazione.

For example i try

```
CarsDatatable.new

or 

Essa::Person::CarsDatatable
```

but I have an error

**Comment by antillas21** [comment]
try ::Essa::Person::CarsDatatable. This will force to start at the root of
all defined modules.

El 12 sep. 2017 08:21, "Alessio" <notifications@github.com> escribió:

I have a rails 3.2 application where I use differents gem that I have
created. I have a folder People and a folder Magazine, so in people I have
a file

module Essa::Person
class CarsDatatable < AjaxDatatablesRails::Base
I want to call CarsDatatable in a external module. How is the syntax to
initialize CarsDatatable in a controller of the folder Magazione.

For example i try

CarsDatatable.new

or

Essa::Person::CarsDatatable

but I have an error

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jbox-web/ajax-datatables-rails/issues/255>, or mute the
thread

**Comment by alessiovaralta** [comment]
Work very frendly thanks
