### ISSUE TITLE
Search error with mysql2 adapter; it doesn't have varchar type

### ISSUE THREAD

**Issue by sebastianiorga** [jbox-web/ajax-datatables-rails#40]
Apparently very easy fix. Changed the cast to CHAR instead of VARCHAR and everything seems to work perfectly.  

```
module AjaxDatatablesRails
  class Base

    private

    def search_condition(column, value)
      model, column = column.split('.')
      model = model.singularize.titleize.gsub( / /, '' ).constantize
      casted_column = ::Arel::Nodes::NamedFunction.new('CAST', [model.arel_table[column.to_sym].as('CHAR')])
      casted_column.matches("%#{value}%")
    end
  end
end
```

Not sure exactly how to check which database adapter is being used and thus dynamically change the cast, I just overrode the method in an initializer.
Loving this gem and datatables :)

**Comment by antillas21** [comment]
Hi @sebastianiorga ,

Thanks for loving our work :)

About the cast into `varchar` or `char`... I am aware that this needs further research on the appropriate setting to handle different db engines... my initial test was with postgre, and there, `char` refers to a single character and `varchar` refers to several characters.

So in my original test-drive, if I set it to `char`, it only yielded one single character from the conversion (casting), typically, the first character... thus, the result was not completely accurate, because when we started adding characters to the search input, the filtered set yielded no results, even though we could prove visually there should have been some.

**Comment by antillas21** [comment]
@sebastianiorga just wanted to let you know that we have released a new version for the gem, and are now properly addressing searching on non text-based columns (and properly casting columns based on the database used in the application).

Please refer to: [README - Searching on non text-based columns](https://github.com/antillas21/ajax-datatables-rails#searching-on-non-text-based-columns) and update to ver. 0.2.1.

Looking forward to your comments.
