### ISSUE TITLE
Incorrect sort columns

### ISSUE THREAD

**Issue by gnilrets** [jbox-web/ajax-datatables-rails#42]
I have an 'id' column that I would like to be in the table, but there is a known bug with using non-string fields in the sortable/searchable definition.  I might be able to live with that for a while, but if I want the 'id' column to be the first column on the page, clicking on a column to sort will sort the wrong column.  With the setup below, when I click on the 'id' column, the table is sorted by 'name'; when I click on the 'name' column, the table gets sorted by 'job_template_type'.  

``` ruby
  def sortable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @sortable_columns ||= [
      'job_specs.name',
      'job_specs.job_template_type',
      'launched_jobs.status'
    ]
  end

  def data
    records.map do |record|
      [
        # comma separated list of the values for each cell of a table row
        # example: record.attribute,
        record.id,
        record.job_spec.name,
        record.job_spec.job_template_type,
        record.status,
      ]
    end
  end
```

**Comment by antillas21** [comment]
Hi @gnilrets 

I would recommend you add the following code in your JS invocation of the datatables table instance:

``` javascript
    $('#table-id').dataTable({
      'processing': true,
      'serverSide': true,
      'ajax': $('#table-id').data('source'),
      'pagingType': 'bootstrap',
      'columns': [
        { 'sortable': false, 'searchable': false },
        { 'sortable': true, 'searchable': true },
        { 'sortable': true, 'searchable': true },
        { 'sortable': true, 'searchable': true }
      ]
    });
```

So that you can have more control over individual properties (searching/sorting) on a column basis.

Also, I would recommend checking our gem master branch, as we have added the ability to search on non-string based fields (dates, integers for example)... we have not released these changes, because we still need to find time fixing and adding specs. We have manually tested it works, but this would not be acceptable to release as is... though, if you need the feature please use the master branch of this repo.

And of course, if you'd like to help us build the missing specs (and fix the current broken ones)... we would appreciate it very much.

**Comment by gnilrets** [comment]
Thanks, I actually was using the master branch, but I had a typo in the `@sortable_columns` array (using the singular instead of plural).  Thanks for your help!
