### ISSUE TITLE
Validation if field value is empty Nillclass

### ISSUE THREAD

**Issue by reyntjensw** [jbox-web/ajax-datatables-rails#88]
Hi

I'm trying to create a datatable but I'd like to add validation like this:
<%= company.company_category.name unless company.company_category.nil? %>

Is this possible in the data section to avoid getting these kind of errors : NoMethodError (undefined method `postalcode' for nil:NilClass)

What I'd like to do is this :
def data
    records.map do |company|
      [
        company.name,
        company.address,
        company.postindex.postalcode unless company.company_category.nil?,
        company.city,
      ]
    end
  end                       

Thanks

**Comment by antillas21** [comment]
@reyntjensw if you do that, that whole line will be missing from the json structure returned by the gem for some records (at least the ones that match the conditional), and thus will cause the jQuery.dataTables plugin to throw an error due to inconsistencies.

What you need to do, is to `tell, don't ask` your object to return a value: either the value expected, or a placeholder in case it does not match the conditional :smile:

**Comment by reyntjensw** [comment]
Hi Antillas, thanks that worked out great!

**Comment by antillas21** [comment]
Glad to have helped.
